baseURL = "https://eckodeath.netlify.app/"
languageCode = "fr-fr"
title = "eckodeath"
theme = "PaperMod"

[params]
  author = "Kurt Grava"
  defaultTheme = "auto" # clair/sombre auto
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowImageInList = true
  ShowImageInSingle = true  # pour l'afficher aussi dans la page d'article

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 2
